# Generated by Django 2.2.1 on 2019-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=10)),
                ('info', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
