# Generated by Django 2.0.1 on 2019-05-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='aboutme',
            field=models.CharField(default='', max_length=100, verbose_name='个人简介'),
        ),
    ]
