# Generated by Django 2.1.2 on 2019-06-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190610_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='id',
            new_name='user_id',
        ),
    ]
